# Generated by Django 5.1 on 2024-10-11 03:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Character",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
                ("level", models.IntegerField(default=1)),
                ("attack_power", models.IntegerField(default=10)),
                ("defense", models.IntegerField(default=0)),
                ("health", models.IntegerField(default=100)),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="character_images/"
                    ),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name="EnergySavingQuiz",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.CharField(max_length=255)),
                ("option_a", models.CharField(max_length=100)),
                ("option_b", models.CharField(max_length=100)),
                ("option_c", models.CharField(max_length=100)),
                ("option_d", models.CharField(max_length=100)),
                ("answer", models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name="Opponent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("challenge_level", models.IntegerField(default=1)),
                ("attack_power", models.IntegerField()),
                ("defense", models.IntegerField()),
                ("health", models.IntegerField()),
                ("coin", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="Users",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                ("user_id", models.CharField(max_length=50, unique=True)),
                ("password", models.CharField(max_length=200)),
                ("name", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=50, unique=True)),
                ("coins", models.IntegerField(default=100)),
                ("energy_count", models.IntegerField(default=0)),
                ("challenge_level", models.IntegerField(default=0)),
                ("coin", models.IntegerField(default=0)),
                ("energy_1", models.IntegerField(default=0)),
                ("energy_2", models.IntegerField(default=0)),
                ("energy_3", models.IntegerField(default=0)),
                ("energy_4", models.IntegerField(default=0)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="LastestEnergyHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField(auto_now_add=True)),
                ("energy_1", models.IntegerField(default=0)),
                ("energy_2", models.IntegerField(default=0)),
                ("energy_3", models.IntegerField(default=0)),
                ("energy_4", models.IntegerField(default=0)),
                ("exp", models.IntegerField()),
                ("gain_exp", models.IntegerField()),
                ("start_time", models.DateTimeField(blank=True, null=True)),
                ("end_time", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Inventory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("character_name", models.CharField(max_length=100)),
                ("level", models.IntegerField(default=1)),
                ("total_experience", models.IntegerField(default=0)),
                ("attack_power", models.IntegerField()),
                ("defense", models.IntegerField()),
                ("health", models.IntegerField()),
                ("is_main_character", models.BooleanField(default=False)),
                ("experience_start", models.IntegerField(default=0)),
                ("gain_exp", models.IntegerField(default=0)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Friendship",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "connected_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="friends",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "friend",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="friend_of",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EnergyHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField(auto_now_add=True)),
                ("amount", models.IntegerField()),
                ("exp", models.IntegerField()),
                ("savings", models.IntegerField()),
                ("start_time", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DailyMission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("clear_count", models.IntegerField(default=0)),
                ("daily_count", models.IntegerField(default=0)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
