# Generated by Django 5.1 on 2024-10-11 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Team_3E", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="dailymission",
            name="last_clear_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
