# Generated by Django 5.1 on 2024-10-14 01:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Team_3E", "0002_dailymission_last_clear_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="MissionTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "mission_type",
                    models.CharField(
                        choices=[
                            ("plug_off", "안 쓰는 콘센트 뽑기"),
                            ("light_off", "사용 안 하는 전등 끄기"),
                        ],
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("description", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="UserMission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_completed", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "mission_template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Team_3E.missiontemplate",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
