# Generated by Django 5.1 on 2024-10-14 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Team_3E", "0003_missiontemplate_usermission"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="friendship",
            name="created_at",
        ),
        migrations.AddField(
            model_name="friendship",
            name="status",
            field=models.CharField(
                choices=[("pending", "Pending"), ("accepted", "Accepted")],
                default=1,
                max_length=20,
            ),
            preserve_default=False,
        ),
    ]
